"""first tables

Revision ID: 1f2b7f828ec9
Revises: 
Create Date: 2025-05-30 15:57:10.606943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2b7f828ec9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_table_name'), ['name'], unique=True)

    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_table_email'), ['email'], unique=True)

    op.create_table('post_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('subtitle', sa.String(length=250), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('img_url', sa.String(length=250), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_table_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_table_title'), ['title'], unique=True)
        batch_op.create_index(batch_op.f('ix_post_table_user_id'), ['user_id'], unique=False)

    op.create_table('association_table',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_table.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_table_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_table_title'))
        batch_op.drop_index(batch_op.f('ix_post_table_date'))

    op.drop_table('post_table')
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_table_email'))

    op.drop_table('user_table')
    with op.batch_alter_table('tag_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_table_name'))

    op.drop_table('tag_table')
    # ### end Alembic commands ###
