"""add name post table

Revision ID: c419c40c89bd
Revises: 1f2b7f828ec9
Create Date: 2025-06-02 12:41:27.082252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c419c40c89bd'
down_revision = '1f2b7f828ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_post_table_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_table_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
